import { MiningPlan } from '@/types';

export const MINING_PLANS: MiningPlan[] = [
  {
    id: 'starter',
    name: 'Starter Plan',
    price: 3500,
    duration: 30,
    hashRate: 10,
    dailyReturn: 500,
    totalReturn: 15000,
    monthlyTasks: 10,
    features: [
      '10 TH/s Mining Power',
      '₦500 Daily Mining Returns',
      '30 Days Duration',
      '10 Tasks Per Month',
      'Basic Support',
      'Withdraw Anytime',
    ],
  },
  {
    id: 'professional',
    name: 'Professional Plan',
    price: 10000,
    duration: 30,
    hashRate: 35,
    dailyReturn: 1500,
    totalReturn: 45000,
    monthlyTasks: 30,
    features: [
      '35 TH/s Mining Power',
      '₦1,500 Daily Mining Returns',
      '30 Days Duration',
      '30 Tasks Per Month',
      'Priority Support',
      'Instant Withdrawals',
      'Referral Bonus 15%',
    ],
    popular: true,
  },
  {
    id: 'elite',
    name: 'Elite Plan',
    price: 25000,
    duration: 30,
    hashRate: 80,
    dailyReturn: 4000,
    totalReturn: 120000,
    monthlyTasks: 60,
    features: [
      '80 TH/s Mining Power',
      '₦4,000 Daily Mining Returns',
      '30 Days Duration',
      '60 Tasks Per Month',
      'VIP Support 24/7',
      'Instant Withdrawals',
      'Referral Bonus 20%',
    ],
  },
  {
    id: 'enterprise',
    name: 'Enterprise Plan',
    price: 50000,
    duration: 30,
    hashRate: 200,
    dailyReturn: 10000,
    totalReturn: 300000,
    monthlyTasks: 100,
    features: [
      '200 TH/s Mining Power',
      '₦10,000 Daily Mining Returns',
      '30 Days Duration',
      '100 Tasks Per Month',
      'Dedicated Account Manager',
      'Instant Withdrawals',
      'Referral Bonus 25%',
      'Free Plan Renewal Discount',
    ],
  },
];
